function JointPos = JointPos(l1,l2,l3,l4,q1,q2,q3,q4)
%JOINTPOS
%    JOINTPOS = JOINTPOS(L1,L2,L3,L4,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Mar-2020 21:23:23

t2 = pi.*(1.0./2.0);
t3 = q1+t2;
t4 = cos(t3);
t5 = l1.*t4;
t6 = sin(t3);
t7 = l1.*t6;
t8 = q2+t2;
t9 = cos(t8);
t10 = l2.*t9;
t11 = sin(t8);
t12 = l2.*t11;
t13 = q3+t2;
t14 = cos(t13);
t15 = l3.*t14;
t16 = sin(t13);
t17 = l3.*t16;
t18 = q4+t2;
JointPos = [0.0*ones(1,length(q1));0.0*ones(1,length(q1));t5;t7;t5+t10;t7+t12;t5+t10+t15;t7+t12+t17;t5+t10+t15+l4.*cos(t18);t7+t12+t17+l4.*sin(t18)];
