function JointVel = JointVel(dq1,dq2,dq3,dq4,l1,l2,l3,l4,q1,q2,q3,q4)
%JOINTVEL
%    JOINTVEL = JOINTVEL(DQ1,DQ2,DQ3,DQ4,L1,L2,L3,L4,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Mar-2020 21:23:23

t2 = pi.*(1.0./2.0);
t3 = q1+t2;
t4 = sin(t3);
t5 = cos(t3);
t6 = dq1.*l1.*t5;
t7 = q2+t2;
t8 = sin(t7);
t9 = cos(t7);
t10 = dq2.*l2.*t9;
t11 = q3+t2;
t12 = sin(t11);
t13 = cos(t11);
t14 = dq3.*l3.*t13;
t15 = q4+t2;
JointVel = [0.0;0.0;-dq1.*l1.*t4;t6;-dq1.*l1.*t4-dq2.*l2.*t8;t6+t10;-dq1.*l1.*t4-dq2.*l2.*t8-dq3.*l3.*t12;t6+t10+t14;-dq4.*l4.*sin(t15)-dq1.*l1.*t4-dq2.*l2.*t8-dq3.*l3.*t12;t6+t10+t14+dq4.*l4.*cos(t15)];
