function relativeJointVel = relativeJointVel(dq1,dq2,dq3,dq4)
%RELATIVEJOINTVEL
%    RELATIVEJOINTVEL = RELATIVEJOINTVEL(DQ1,DQ2,DQ3,DQ4)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Mar-2020 21:23:23

relativeJointVel = [dq1;dq1-dq2;dq2-dq3;dq3-dq4;dq4];
