function relativeJointPos = relativeJointPos(q1,q2,q3,q4)
%RELATIVEJOINTPOS
%    RELATIVEJOINTPOS = RELATIVEJOINTPOS(Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Mar-2020 21:23:23

relativeJointPos = [q1;q1-q2;q2-q3;q3-q4;q4];
